export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const SET_PROFILE = 'SET_PROFILE';

export const MARK_ALL_READ_NOTIFICATION = 'MARK_ALL_READ_NOTIFICATION';
export const MARK_ALL_READ_FAIL = 'MARK_ALL_READ_FAIL';

export const GET_CONTACT_INFO = 'GET_CONTACT_INFO';

export const LOADING_PROPERTY = 'LOADING_PROPERTY';
export const GET_COUNT = 'GET_COUNT';
export const GET_PROPERTIES = 'GET_PROPERTIES';
export const REMOVE_PROPERTIES = 'REMOVE_PROPERTIES';
export const GET_PROPERTY = 'GET_PROPERTY';
export const PROPERTY_ERROR = 'PROPERTY_ERROR';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const DISTANCE_ERROR = 'DISTANCE_ERROR';

export const GET_PROPERTY_TYPES = 'GET_PROPERTY_TYPES';
export const PROPERTY_TYPES_ERROR = 'PROPERTY_TYPES_ERROR';
export const UPDATE_REMAIN_TIME = 'UPDATE_REMAIN_TIME';
export const COUNTING_DOWN = 'COUNTING_DOWN';

export const LOADING_BIDS = 'LOADING_BIDS';
export const GET_BIDS = 'GET_BIDS';
export const ADD_BID = 'ADD_BID';
export const UPDATE_BID = 'UPDATE_BID';
export const DELETE_BID = 'DELETE_BID';
export const BID_ERROR = 'BID_ERROR';

export const GET_LISTING_NOW = 'GET_LISTING_NOW';

export const GET_MY_PROPERTIES = 'GET_MY_PROPERTIES';



export const UPDATE_LIKES = 'UPDATE_LIKES';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
